---
- name: exercice_dev_ops
  hosts: dev1,prod1
  become: yes
  vars_files:
  - vars/assignment_users.yaml
  tasks:
  - name: user exists per its role
    user:
      name: "{{ item.name }}"
      state: present
    loop: "{{ assignment_users }}"
    when: (item.role == 'developer' and 'dev' in group_names) or (item.role == 'ops' and 'prod' in group_names)