---
- name: gatherfacts exercice
  hosts: ec2
  become: yes
  vars_files: vars/vars_file.yaml
  tasks:
  - name: create file
    copy: 
      content: |
        distribution : {{ ansible_facts.distribution }}
        distribution release : {{ ansible_facts.distribution_release }}
        total memory : {{ ansible_facts.memtotal_mb }}
        distribution version : {{ ansible_facts.distribution_version }}
        nbre cpu core: {{ ansible_facts.processor_cores }}
      dest: /tmp/report           
