---
- name: user exercice
  hosts: ec2
  become: yes
  vars_files:
  - vars/users.yaml
  tasks:
  - name: add group
    group: 
      name: "{{ assignment_group }}"
      state: present
  - name : add user
    user:
      name: "{{ assignment_user_name }}"
      uid: "{{ assignment_user_id }}"
      state: present
      group: "{{ assignment_group }}"
      append: yes
